[package]
name = "bincode_reloaded_derive"
version = "3.1.21" # remember to update bincode_reloaded
authors = [
    "Zoey Riordan <zoey@dos.cafe>",
    "Victor Koenders <bincode@trangar.com>",
    "Chris Butler <chris.butler@butlergroup.net>",
]
edition = "2024"
rust-version = "1.86.0"

repository = "https://github.com/butlergroup/bincode_reloaded"
documentation = "https://docs.rs/bincode_reloaded_derive"
readme = "./readme.md"
categories = ["encoding", "data-structures", "development-tools", "parsing"]
keywords = ["binary", "encode", "decode", "serialize", "deserialize"]
license = "MIT"
description = "Implementation of #[derive(Encode, Decode)] for bincode_reloaded"

[lib]
proc-macro = true

[dependencies]
virtue = "0.0.19"
